# Create a Basic NN for Image Classification on the Fashion MNIST Dataset

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tensorflow import keras

2023-06-23 12:37:12.520848: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-06-23 12:37:12.520869: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


Load the Fashion MNIST dataset from the keras API.

In [2]:
dataset = tf.keras.datasets.fashion_mnist

Split the data into training and testing datasets.

In [3]:
(XTrain, yTrain), (XTest, yTest) = dataset.load_data()

Here's how the training data looks. We can see that it's 60000 images each with 28x28 pixel values ranging from 0-255.

In [4]:
XTrain.shape, yTrain.shape

((60000, 28, 28), (60000,))

Now checking to see whether we can visualise the 987th image in the training images dataset.

In [5]:
index = 987

In [6]:
np.set_printoptions(linewidth=300)

image = XTrain[index]
label = yTrain[index]

print(f'Label: {label}\nImage Pixel Values:\n{image}')
plt.imshow(image, cmap='Greys')

Label: 6
Image Pixel Values:
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0  23 190 121 173 133   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   1   0   0   3   0   0   0   3 178 220 173 202 224  37   0   0   0   0   1   0]
 [  0   0   0   0   0   0   0   0   1   2   3   0   7  96 153 193 206 221 219 205 193 186 170 110  34   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0  23 172 178 182 149 176 232 191 170 207 146 169 181 168  97   0   0]
 [  0   0   0   0   0   0   0   5   6  15   0 139 191 145 169 172 157 159 186 166 153 159 143 146 160 205   0   0]
 [  0   0   0   0   0   0  14  42   0   8   0 176 222 175 168 167 160 170 160 166 164 158 155 156 164 188  33   0]
 [  0   0   0   1   7   0  15  33  73  65  34   0  71 145 209 207 166 163 163 164 159 154 158 138 192 188 103   0]
 [  0   0   6  10   7   8   9   3  70  34  32   0  

Now, before we create a neural network and pass this data to train it, we need to normalise our data. We do this by dividing every pixel value in all the images across the datasets by 255.

In [7]:
XTrain = XTrain / 255.0
XTest = XTest / 255.0

Checking the documentation for the `Flatten` layer that we can import as `tf.keras.layers.Flatten()`.

In [8]:
tf.keras.layers.Flatten??

Init signature: tf.keras.layers.Flatten(data_format=None, **kwargs)
Source:        
@keras_export('keras.layers.Flatten')
class Flatten(Layer):
  """Flattens the input. Does not affect the batch size.

  Note: If inputs are shaped `(batch,)` without a feature axis, then
  flattening adds an extra channel dimension and output shape is `(batch, 1)`.

  Args:
    data_format: A string,
      one of `channels_last` (default) or `channels_first`.
      The ordering of the dimensions in the inputs.
      `channels_last` corresponds to inputs with shape
      `(batch, ..., channels)` while `channels_first` corresponds to
      inputs with shape `(batch, channels, ...)`.
      It defaults to the `image_data_format` value found in your
      Keras config file at `~/.keras/keras.json`.
      If you never set it, then it will be "channels_last".

  Example:

  >>> model = tf.keras.Sequential()
  >>> model.add(tf.keras.layers.Conv2D(64, 3, 3, input_shape=(3, 32, 32)))
  >>> model.output_shape
  (N

Define our model to be a sequential model with the following layers:
1. A flatten layer to convert a 28x28 image (2D array of pixel intensities) to a 1D array
2. A dense layer to process and extract features with an activation of relu
3. An output layer (dense) with 10 cells corresponding to the 10 output classes with an activation of softmax to get the probabilities 

In [9]:
model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(128, activation=tf.nn.relu),
        tf.keras.layers.Dense(10, activation=tf.nn.softmax)
    ]
)

2023-06-23 12:37:14.866063: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-23 12:37:14.866361: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-06-23 12:37:14.866406: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory
2023-06-23 12:37:14.866467: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory
2023-06-23 12:37:14.866575: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Co

Now, compiling the model using the `Adam` optimiser and sparse categorical cross-entropy as our loss metric.

In [10]:
model.compile(
    optimizer=tf.optimizers.Adam(),
    loss='sparse_categorical_crossentropy',
    # These'll show at the side of each epoch in the training output
    metrics=['Accuracy']
)

Training the model now for a specified number of epochs. It's worth changing this number to see how the training and testing accuracies are affected. 

In [11]:
EPOCHS = 20
history = model.fit(XTrain, yTrain, epochs=EPOCHS)

Epoch 1/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.4951 - Accuracy: 0.8260
Epoch 2/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3722 - Accuracy: 0.8668
Epoch 3/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3345 - Accuracy: 0.8783
Epoch 4/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.3100 - Accuracy: 0.8867
Epoch 5/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2941 - Accuracy: 0.8925
Epoch 6/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2796 - Accuracy: 0.8977
Epoch 7/20
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2669 - Accuracy: 0.9002
Epoch 8/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2569 - Accuracy: 0.9051
Epoch 9/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2472 - Accuracy: 0.9072
Epoch 10/20
1875/1875 [==============================] - 3s 1ms/step - loss: 0.238

Checking the loss and accuracy of the testing data to see whether our model has overfit or not. It's of the form `[loss, accuracy]`.

In [12]:
model.evaluate(XTest, yTest)

313/313 [==============================] - 1s 1ms/step - loss: 0.3534 - Accuracy: 0.8864


[0.3533775806427002, 0.8863999843597412]

In [13]:
image.shape

(28, 28)

In [14]:
image = np.expand_dims(image, axis=0)
image.shape

(1, 28, 28)

In [15]:
predictions = model.predict(image)

In [16]:
predictions, predictions.shape

(array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]], dtype=float32), (1, 10))

In [17]:
print(f'True Label: {label}\nPredicted Label: {np.argmax(predictions)}')

True Label: 6
Predicted Label: 6


In [18]:
# Access the accuracy values for each epoch
accuracyLog = history.history['Accuracy']

In [20]:
# Plot the accuracy values
plt.style.use('seaborn')

plt.figure(figsize=(8, 6), dpi=120)

plt.title('Training Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')

plt.plot(range(1, EPOCHS + 1), accuracyLog)

plt.show()

---